const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");
const path = require("node:path");
const test = require("node:test");

require("../reddit-dom-selectors.js");

const selectors = globalThis.RedditRpaDomSelectors;
const fixture = JSON.parse(readFileSync(path.join(__dirname, "fixtures", "reddit_dom_descriptors.json"), "utf8"));
const collectorConfig = readFileSync(path.join(__dirname, "..", "collector-config.js"), "utf8");
const contentScript = readFileSync(path.join(__dirname, "..", "content.js"), "utf8");
const recordExtractor = readFileSync(path.join(__dirname, "..", "content-record-extractor.js"), "utf8");
const commandRegistry = readFileSync(path.join(__dirname, "..", "content-command-registry.js"), "utf8");
const listingSelection = readFileSync(path.join(__dirname, "..", "listing-selection.js"), "utf8");
const popupScript = readFileSync(path.join(__dirname, "..", "popup.js"), "utf8");
const popupMarkup = readFileSync(path.join(__dirname, "..", "popup.html"), "utf8");
const serviceWorker = readFileSync(path.join(__dirname, "..", "service-worker.js"), "utf8");

test("keeps fixed Reddit DOM selector coverage for posts and comment hierarchy", () => {
  assert.ok(selectors.postNodes.includes("shreddit-post"));
  assert.ok(selectors.commentNodes.includes("shreddit-comment"));
  assert.ok(selectors.commentParentAttributes.includes("parent-fullname"));
  assert.ok(selectors.commentPostAttributes.includes("post-fullname"));
  assert.ok(selectors.commentContent.includes("shreddit-comment-body"));
  assert.equal(selectors.postTitle.includes("h1"), false);
  assert.match(recordExtractor, /function postTitle\(node, postFullname\)/);
  assert.match(recordExtractor, /function commentOwnershipEvidence\(node, context, commentFullname\)/);
  assert.match(recordExtractor, /function nativeCommentParentHints\(nodes, collapsedPlaceholderCount = 0\)/);
  assert.match(recordExtractor, /comment-parent-positions/);
  assert.match(recordExtractor, /model\.resolveNativeCommentParents/);
  assert.match(recordExtractor, /model\.diagnoseNativeCommentTree/);
  assert.match(recordExtractor, /tree_diagnostics/);
  assert.match(recordExtractor, /function collectThread\(context, \{ collapsedPlaceholderCount = 0 \} = \{\}\)/);
  assert.match(recordExtractor, /rejected_foreign_comment_count/);
  assert.match(contentScript, /targetPostCount/);
  assert.match(contentScript, /maxPosts/);
  assert.match(recordExtractor, /function mergeListingRecords\(existing, incoming, limit/);
  assert.match(contentScript, /stopReason = "target_post_count"/);
  assert.match(recordExtractor, /model\.postPermalinkIssue\(record\.canonical_url, record\.fullname, context\.subreddit\)/);
  assert.match(contentScript, /function watchPageNavigation\(\)/);
  assert.match(contentScript, /window\.setInterval\(/);
  assert.match(contentScript, /function resumeActiveJobForCurrentPage\(\)/);
  assert.match(contentScript, /function navigateOrResumeThread\(url, \{ forceReload = false \} = \{\}\)/);
  assert.match(contentScript, /function dispatchThreadNavigation\(\{ url, forceReload = false \}\)/);
  assert.match(contentScript, /let commandResponsePending = false/);
  assert.match(contentScript, /function flushDeferredThreadNavigation\(\)/);
  assert.match(contentScript, /sendResponse\(result\);\s+commandResponsePending = false;\s+flushDeferredThreadNavigation\(\);/);
  assert.match(contentScript, /location\.reload\(\)/);
  assert.match(contentScript, /function threadSettleDelay\(config = \{\}\)/);
  assert.match(contentScript, /function threadSettlePlan\(config = \{\}, random = Math\.random\)/);
  assert.match(contentScript, /async function captureStableThreadPage\(job, config, settleWaitMs\)/);
  assert.match(contentScript, /model\.shouldRecheckZeroCommentCapture/);
  assert.match(contentScript, /function startThreadProgressWatchdog\(job, pageUrl\)/);
  assert.match(contentScript, /function syncAndStartBatch\(config = \{\}\)/);
  assert.match(contentScript, /async function knownListingPostState\(context\)/);
  assert.match(contentScript, /skipExisting/);
  assert.match(contentScript, /status: "no_unseen_posts"/);
  assert.match(contentScript, /candidatePostLimit: safeSkipExisting \? 500 : safeCount/);
  assert.match(listingSelection, /function selectUnseenRecords\(records, knownPosts, limit\)/);
  assert.match(serviceWorker, /async function listKnownPostFullnames\(context\)/);
  assert.match(serviceWorker, /skip_existing: request\.skip_existing/);
  assert.match(contentScript, /function startLatestListingBatch\(config = \{\}\)/);
  assert.match(contentScript, /async function cancelBatch\(\)/);
  assert.match(contentScript, /commandRegistry\.execute\(message\)/);
  assert.match(commandRegistry, /function create\(entries = \[\]\)/);
  assert.match(commandRegistry, /capturesFailure/);
  assert.match(contentScript, /\["cancelBatch", \(\) => cancelBatch\(\)\]/);
  assert.match(contentScript, /\["startLatestListingBatch", \(message\) => startLatestListingBatch\(message\.config \|\| \{\}\), \{ captureFailure: true \}\]/);
  assert.match(contentScript, /function persistBatchProgress\(batch = state\.activeBatchJob\)/);
  assert.match(contentScript, /navigateOrResumeThread\(target\.permalink, \{ forceReload: true \}\)/);
  assert.match(popupScript, /syncAndStartBatch/);
  assert.match(popupScript, /startLatestListingBatch/);
  assert.match(collectorConfig, /const DEFAULT_CONFIG = Object\.freeze\(\{/);
  assert.match(popupScript, /import "\.\/collector-config\.js"/);
  assert.match(popupScript, /const \{ DEFAULT_CONFIG \} = collectorConfig/);
  assert.match(popupScript, /function positiveInputValue\(id, fallback\)/);
  assert.match(popupScript, /targetPostCount: positiveInputValue\("targetPostCount", DEFAULT_CONFIG\.targetPostCount\)/);
  assert.match(popupMarkup, /同步当前列表/);
  assert.match(popupMarkup, /开始采集 25 帖/);
  assert.match(popupMarkup, /高级设置/);
  assert.match(contentScript, /function requiresOutputPermission\(error\)/);
  assert.match(contentScript, /batch_paused_output_permission_required/);
  assert.match(contentScript, /reddit-rpa-claim-worker/);
  assert.match(contentScript, /reddit-rpa-restore-worker/);
  assert.match(contentScript, /worker_token/);
  assert.match(contentScript, /storageError\.code = result\?\.code/);
  assert.equal(fixture.listing.posts.length, 2);
  assert.equal(fixture.thread.post.postId, "abc123");
  assert.equal(fixture.thread.comments[0].parentFullname, "t3_abc123");
  assert.equal(fixture.thread.comments[1].parentFullname, "t1_def456");
});

test("keeps rejected foreign comments out of the snapshot without turning a complete capture into manual", () => {
  const coverageAssessment = contentScript.match(/function coverageAssessment\(job, quality\) \{[\s\S]*?\n  \}\n\n  async function storeCompletedThread/);
  assert.ok(coverageAssessment, "coverage assessment should remain a discrete audit boundary");
  assert.match(coverageAssessment[0], /rejected_foreign_comment_count/);
  assert.doesNotMatch(coverageAssessment[0], /rejected_foreign_comment_count\) > 0\) reasons\.push/);
  assert.match(popupScript, /const reviewRequired = \["manual_review_required", "batch_manual_review_required", "batch_paused_output_permission_required", "batch_rate_limited", "batch_rate_limited_manual_review"\]/);
  const manualReviewStatus = popupScript.indexOf('if (["batch_manual_review_required", "manual_review_required"].includes(status))');
  const genericFailureStatus = popupScript.indexOf('if (value.ok === false || value.error)');
  assert.ok(manualReviewStatus >= 0 && manualReviewStatus < genericFailureStatus, "manual review must be shown as a review warning before the generic failure branch");
});

test("keeps a fully verified native comment snapshot distinct from Reddit's header count", () => {
  const coverageAssessment = contentScript.match(/function coverageAssessment\(job, quality\) \{[\s\S]*?\n  \}\n\n  async function storeCompletedThread/);
  assert.ok(coverageAssessment);
  assert.match(coverageAssessment[0], /visibleCommentCount: job\.native_comment_dom_observed/);
  assert.match(contentScript, /coverage_status: coverage\.status \|\| status/);
  assert.match(contentScript, /visible_comment_count: coverage\.visible_comment_count/);
});

test("keeps the daily two-step popup flow wired to existing controls", () => {
  const ids = new Set([...popupMarkup.matchAll(/\bid="([^"]+)"/g)].map((match) => match[1]));
  const referencedIds = [...popupScript.matchAll(/element\("([^"]+)"\)/g)].map((match) => match[1]);
  for (const id of referencedIds) assert.ok(ids.has(id), `popup.js references missing #${id}`);
  assert.equal((popupMarkup.match(/id="runListing"/g) || []).length, 1);
  assert.equal((popupMarkup.match(/id="startLatestBatch"/g) || []).length, 1);
  assert.match(popupMarkup, /id="chooseOutputRoot"/);
  assert.match(popupMarkup, /id="reconnectOutputRoot"/);
  assert.match(popupMarkup, /id="batchControls" class="batch-controls"/);
  assert.match(popupMarkup, /暂停当前批次/);
  assert.match(popupMarkup, /继续当前批次/);
  assert.match(popupMarkup, /id="cancelBatch"/);
  assert.match(popupScript, /command\("cancelBatch"\)/);
  assert.doesNotMatch(popupScript, /chooseOutputRoot"\)\.hidden/);
  assert.match(popupMarkup, /id="targetPostCount"[^>]*value="25"/);
  assert.match(popupMarkup, /id="maxPosts"[^>]*value="25"/);
  const startLatest = contentScript.match(/async function startLatestListingBatch\(config = \{\}\) \{[\s\S]*?\n  \}/);
  assert.ok(startLatest, "daily step 2 should stay separate from list sync");
  assert.match(startLatest[0], /state\.lastResult\?\.mode !== "listing_sync"/);
  assert.match(startLatest[0], /listingBatchTargets\(records\)/);
  const cancelBatch = contentScript.match(/async function cancelBatch\(\) \{[\s\S]*?\n  \}\n\n  async function resumeBatch/);
  assert.ok(cancelBatch, "batch cancellation should remain a discrete safe boundary");
  assert.match(cancelBatch[0], /worker\.active && !worker\.owner/);
  assert.match(cancelBatch[0], /await verifyWritableOutputRoot\(\)/);
  assert.match(cancelBatch[0], /clearPendingThreadNavigation\(\)/);
  assert.match(cancelBatch[0], /batchQueue\.cancel\(batch, cancelledAt, "manual"\)/);
  assert.match(cancelBatch[0], /Object\.assign\(batch, priorBatchState\)/);
  assert.match(cancelBatch[0], /releaseBatchWorker\(batch\)/);
  assert.match(contentScript, /async function repairCancelledBatchManifest\(\)/);
  assert.match(contentScript, /\["repairCancelledBatch", \(\) => repairCancelledBatchManifest\(\)\]/);
  assert.match(popupScript, /command\("repairCancelledBatch"\)/);
});

test("keeps a paused batch recoverable when directory permission expires", () => {
  assert.match(popupScript, /let outputRootPermission = "none"/);
  assert.match(popupScript, /reconnectOutputRoot"\)\.disabled = isBusy \|\| !outputRootConfigured \|\| \(batchRunning && !batchPaused\)/);
  assert.match(popupScript, /resumeBatch"\)\.disabled = isBusy \|\| !batchPaused \|\| !outputRootWritable/);
  assert.match(popupScript, /async function ensureOutputRootWritable\(\)/);
  assert.match(popupScript, /writableCommand\("runListing"/);
  assert.match(popupScript, /writableCommand\("startLatestListingBatch"/);
  assert.match(popupScript, /需要恢复授权/);
  assert.match(contentScript, /async function verifyWritableOutputRoot\(\)/);
  assert.match(contentScript, /reddit-rpa-output-root-preflight/);
  assert.match(contentScript, /async function pauseBatchForOutputPermission\(batch, error\)/);
  assert.match(contentScript, /async function pauseBatchForRateLimit\(batch, error\)/);
  assert.match(contentScript, /RATE_LIMIT_PAGE_TEXT/);
  assert.match(contentScript, /PAGE_NAVIGATION_TIMEOUT/);
  const resumeBatch = contentScript.match(/async function resumeBatch\(\{ allowRateLimitCooldown = false, rateLimitResume = false \} = \{\}\) \{[\s\S]*?\n  \}/);
  assert.ok(resumeBatch, "resume must retain an explicit output preflight");
  assert.match(resumeBatch[0], /await verifyWritableOutputRoot\(\)/);
  assert.match(serviceWorker, /reddit-rpa-output-root-preflight/);
  assert.match(serviceWorker, /loadWritableOutputRoot\(\)/);
  assert.match(serviceWorker, /rate_limited/);
});

test("lets a newly injected script take over after an extension reload", () => {
  assert.match(contentScript, /CONTENT_SCRIPT_CONTROLLER_KEY/);
  assert.doesNotMatch(contentScript, /if \(globalThis\.__redditRpaContentScriptLoaded\) return/);
  assert.match(contentScript, /globalThis\[CONTENT_SCRIPT_CONTROLLER_KEY\]\?\.dispose\?\.\(\)/);
  assert.match(contentScript, /function disposeController\(\)/);
  assert.match(contentScript, /function sendRuntimeMessage\(message\)/);
  assert.match(contentScript, /return sendRuntimeMessage\(\{\s+type: "reddit-rpa-worker-status"/);
  assert.match(contentScript, /type: "reddit-rpa-restore-worker"/);
  assert.match(contentScript, /batch\.worker_token = restored\.worker_token/);
  assert.match(contentScript, /if \(extensionContextInvalidated\(error\)\) \{\s+\/\/ 这是扩展重载前的旧脚本；停止它，交给新注入的控制器接管。\s+disposeController\(\);\s+return;/);
  assert.match(contentScript, /pageNavigationWatcher = window\.setInterval/);
  assert.match(contentScript, /chrome\.runtime\.onMessage\.addListener\(commandMessageListener\)/);
  assert.match(serviceWorker, /The message port closed before a response was received/);
  assert.match(serviceWorker, /Extension context invalidated/);
  assert.match(serviceWorker, /function expectedContentScriptVersion\(\)/);
  assert.match(serviceWorker, /\{ command: "status" \}/);
  assert.match(serviceWorker, /status\?\.version \|\| ""\) !== expectedContentScriptVersion\(\)/);
  assert.match(serviceWorker, /injectCurrentContentScript\(tabId\)/);
  assert.match(serviceWorker, /async function restoreWorker\(sender, batchId, expectedTabId = null\)/);
  assert.match(serviceWorker, /current\.tab_id !== tabId/);
  assert.match(serviceWorker, /current\.batch_id !== requestedBatchId/);
  assert.match(serviceWorker, /status: "worker_restored"/);
  assert.match(serviceWorker, /reddit-rpa-restore-worker/);
});
